# Generated by Django 3.2.7 on 2021-09-02 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='content',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='drf_app.section'),
            preserve_default=False,
        ),
    ]
